apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/London"
            - name: VERSION
              value: "docker"
          ports:
            - name: plex
              containerPort: 32400
              protocol: TCP
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-media
              mountPath: /media
            - name: plex-transcode
              mountPath: /transcode
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: plex-media
          persistentVolumeClaim:
            claimName: plex-media
        - name: plex-transcode
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
spec:
  selector:
    app: plex
  type: ClusterIP
  ports:
    - name: plex
      port: 32400
      targetPort: 32400
      protocol: TCP
